baseURL = "https://localhost:1313/"
languageCode = "en-us"
title = "Jorge Zamora Rey"
theme = "terminal"

[pagination]
pagerSize = 10

[params]
contentTypeName = "posts"
themeColor = "green"
showMenuItems = 4
fullWidthTheme = false
centerTheme = true

[languages]
  [languages.en]
    languageName = "English"
    title = "Jorge Zamora Rey"
    subtitle = "NLP / ML Systems / Computer Engineering"
    owner = "Jorge Zamora Rey"

    [languages.en.params.logo]
      logoText = "reddrex@cv ~"
      logoHomeLink = "/"

    [languages.en.menu]
      [[languages.en.menu.main]]
        identifier = "cv"
        name = "CV"
        url = "/cv/"
        weight = 1

      [[languages.en.menu.main]]
        identifier = "projects"
        name = "Projects"
        url = "/projects/"
        weight = 2

      [[languages.en.menu.main]]
        identifier = "publications"
        name = "Publications & others"
        url = "/publications/"
        weight = 3

      [[languages.en.menu.main]]
        identifier = "contact"
        name = "Contact"
        url = "/contact/"
        weight = 4

[module]
  [module.hugoVersion]
    extended = true
    min = '0.90.0'

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true
